database:
  dialect: sqlite3
  host:  book.db
  port:
  dbname: 
  username: 
  password: 
  migration: true

extension:
  master_generator: true
  cors_enabled: true
  security_enabled: true

log:
  format: ${time_rfc3339} [${level}] ${remote_ip} ${method} ${uri} ${status}
  level: 1
  file_path: 

security:
  exclude_path:
    - /api/account/login
    - /api/account/logout
    - /api/health