name: check

on:
  pull_request:
    branches: [ master ]

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      # Set up GOPATH
      - name: set up
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
        id: go
      # Check out this repository
      - name: checkout
        uses: actions/checkout@v3
      # Store cache
      - name: cache
        uses: actions/cache@v2.1.7
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      # Run golangci-lint using reviewdog
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.github_token }}
          level: warning
          golangci_lint_flags: "--config=.github/.golangci.yml"
          reporter: github-pr-review
      # Run test
      - name: test
        run: go test -cover ./...
